SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `u534143670_multi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `u534143670_multi` ;

-- -----------------------------------------------------
-- Table `u534143670_multi`.`TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`TIPO` (
  `COD_TIPO` INT NOT NULL,
  `TIPO_USUARIO` CHAR(3) NOT NULL,
  PRIMARY KEY (`COD_TIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`IMAGEM_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`IMAGEM_USUARIO` (
  `COD_IMAGEM` INT NOT NULL AUTO_INCREMENT,
  `URL_IMAGEM` VARCHAR(20) NOT NULL,
  `COD_IMAGEM_USUARIO` INT NOT NULL,
  PRIMARY KEY (`COD_IMAGEM`),
  INDEX `COD_IMAGEM_USUARIO_idx` (`COD_IMAGEM_USUARIO` ASC),
  CONSTRAINT `COD_IMAGEM_USUARIOS`
    FOREIGN KEY (`COD_IMAGEM_USUARIO`)
    REFERENCES `u534143670_multi`.`USUARIO` (`COD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`DESATIVADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`DESATIVADOS` (
  `COD_DESATIVADO` INT NOT NULL,
  `NOME_DESATIVADO` VARCHAR(45) NOT NULL,
  `EMAIL_DESATIVADO` VARCHAR(45) NOT NULL,
  `SENHA_DESATIVADO` VARCHAR(45) NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `TEMPO_DESATIVADO` TIME NOT NULL,
  `MOTIVO_DESATIVADO` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`COD_DESATIVADO`),
  UNIQUE INDEX `EMAIL_DESATIVADO_UNIQUE` (`EMAIL_DESATIVADO` ASC),
  UNIQUE INDEX `COD_DESATIVADO_UNIQUE` (`COD_DESATIVADO` ASC),
  CONSTRAINT `COD_IMAGEMS`
    FOREIGN KEY (`COD_DESATIVADO`)
    REFERENCES `u534143670_multi`.`IMAGEM_USUARIO` (`COD_IMAGEM_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`USUARIO` (
  `COD_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(45) NOT NULL,
  `EMAIL_USUARIO` VARCHAR(45) NOT NULL,
  `SENHA_USUARIO` VARCHAR(60) NOT NULL,
  `TIPO_USUARIO` INT NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `USUARIO_DESATIVADO` INT NULL,
  PRIMARY KEY (`COD_USUARIO`),
  UNIQUE INDEX `COD_COLUNISTA_UNIQUE` (`COD_USUARIO` ASC),
  UNIQUE INDEX `EMAIL_COLUNISTA_UNIQUE` (`EMAIL_USUARIO` ASC),
  INDEX `TIPO_USUARIO_idx` (`TIPO_USUARIO` ASC),
  INDEX `USUARIO_DESATIVADO_idx` (`USUARIO_DESATIVADO` ASC),
  UNIQUE INDEX `USUARIO_DESATIVADO_UNIQUE` (`USUARIO_DESATIVADO` ASC),
  CONSTRAINT `TIPO_USUARIOS`
    FOREIGN KEY (`TIPO_USUARIO`)
    REFERENCES `u534143670_multi`.`TIPO` (`COD_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USUARIO_DESATIVADOS`
    FOREIGN KEY (`USUARIO_DESATIVADO`)
    REFERENCES `u534143670_multi`.`DESATIVADOS` (`COD_DESATIVADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`COMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`COMENT` (
  `COD_COMENT` INT NOT NULL AUTO_INCREMENT,
  `COD_USUARIO` INT NOT NULL,
  `CONTEUDO_COMENT` TEXT NULL,
  `DATA_COMENT` DATE NOT NULL,
  `HORA_COMENT` TIME NOT NULL,
  PRIMARY KEY (`COD_COMENT`),
  INDEX `COMENT_USUARIO_idx` (`COD_USUARIO` ASC),
  CONSTRAINT `COMENT_USUARIOS`
    FOREIGN KEY (`COD_USUARIO`)
    REFERENCES `u534143670_multi`.`USUARIO` (`COD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`CONSOLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`CONSOLES` (
  `COD_CONSOLE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CONSOLE` VARCHAR(45) NOT NULL,
  `EMPRESA_CONSOLE` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_CONSOLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`ARTIGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`ARTIGO` (
  `ID_ARTIGO` INT NOT NULL AUTO_INCREMENT,
  `TITULO_ARTIGO` VARCHAR(60) NOT NULL,
  `CATEGORIA_ARTIGO` VARCHAR(30) NOT NULL,
  `DESCRICAO_ARTIGO` TEXT NOT NULL,
  `CONTEUDO_ARTIGO` TEXT NOT NULL,
  `DATA_ARTIGO` DATE NOT NULL,
  `HORA_ARTIGO` TIME NOT NULL,
  `AUTOR_ARTIGO` VARCHAR(50) NOT NULL,
  `COD_COMENTARIO` INT NOT NULL,
  `CONSOLE_ARTIGO` INT NOT NULL,
  PRIMARY KEY (`ID_ARTIGO`),
  UNIQUE INDEX `ID_ARTIGO_UNIQUE` (`ID_ARTIGO` ASC),
  UNIQUE INDEX `COD_COMENTARIO_UNIQUE` (`COD_COMENTARIO` ASC),
  INDEX `ARTIGO_CONSOLE_idx` (`CONSOLE_ARTIGO` ASC),
  CONSTRAINT `COMENT_ARTIGOS`
    FOREIGN KEY (`COD_COMENTARIO`)
    REFERENCES `u534143670_multi`.`COMENT` (`COD_COMENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARTIGO_CONSOLES`
    FOREIGN KEY (`CONSOLE_ARTIGO`)
    REFERENCES `u534143670_multi`.`CONSOLES` (`COD_CONSOLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`CANDIDATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`CANDIDATO` (
  `COD_CANDIDATO` INT NOT NULL AUTO_INCREMENT,
  `NOME_CANDIDATO` VARCHAR(45) NOT NULL,
  `EMAIL_CANDIDATO` VARCHAR(45) NOT NULL,
  `CURRICULO_CANDIDATO` BLOB NOT NULL,
  `IDADE_CANDIDATO` CHAR(2) NOT NULL,
  `URL_PORTFOLIO` VARCHAR(65) NOT NULL,
  UNIQUE INDEX `EMAIL_CANDIDATO_UNIQUE` (`EMAIL_CANDIDATO` ASC),
  PRIMARY KEY (`COD_CANDIDATO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`ACOES_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`ACOES_LOG` (
  `COD_ACOES_LOG` INT NOT NULL,
  `NOME_ACAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_ACOES_LOG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u534143670_multi`.`LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u534143670_multi`.`LOG` (
  `COD_LOG` INT NOT NULL AUTO_INCREMENT,
  `IP_LOG` VARCHAR(45) NOT NULL,
  `DATA_LOG` DATE NOT NULL,
  `HORA_LOG` TIME NOT NULL,
  `MENSAGEM_LOG` VARCHAR(45) NOT NULL,
  `ACAO_LOG` INT NOT NULL,
  `AUTOR_LOG` VARCHAR(45) NOT NULL,
  `COD_AUTOR_LOG` INT NOT NULL,
  PRIMARY KEY (`COD_LOG`),
  INDEX `COD_AUTOR_LOG_idx` (`COD_AUTOR_LOG` ASC),
  INDEX `COD_ACAO_idx` (`ACAO_LOG` ASC),
  CONSTRAINT `COD_AUTOR_LOG`
    FOREIGN KEY (`COD_AUTOR_LOG`)
    REFERENCES `u534143670_multi`.`USUARIO` (`COD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COD_ACAO`
    FOREIGN KEY (`ACAO_LOG`)
    REFERENCES `u534143670_multi`.`ACOES_LOG` (`COD_ACOES_LOG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (1, 'Efetuo Login');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (2, 'Alterou Foto');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (3, 'Desativado');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (4, 'Deletado');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (5, 'Reativado');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (6, 'Alterou Senha');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (7, 'Alterou Email');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (8, 'Alterou Nome de Perfil');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (9, 'Comentou');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (10, 'Cadastro No Site');
INSERT INTO u534143670_multi.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (11, 'Efetuo Logout');
	
INSERT INTO u534143670_multi.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (1, 'ADM');
INSERT INTO u534143670_multi.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (2, 'RES');
INSERT INTO u534143670_multi.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (3, 'COL');
INSERT INTO u534143670_multi.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (4, 'DES');

INSERT INTO u534143670_multi.USUARIO (`NOME_USUARIO`, `EMAIL_USUARIO`, `SENHA_USUARIO`, `TIPO_USUARIO`, `DATA_NASCIMENTO`, `USUARIO_DESATIVADO`, `LOG_USUARIO`) 
	VALUES ('Administrador', 'admin@admin.com', 'admin', 1, '2014-08-12', NULL, NULL);

	
